[package]
authors = ["melkor <hohav@fastmail.com>", "Vlad Firoiu <vladfi2@gmail.com>"]
name = "peppi-py-vladfi"
version = "0.9.2"
edition = "2024"

[lib]
name = "peppi_py"
crate-type = ["cdylib"]

[dependencies]
arrow2 = "0.17"
peppi = { git = "https://github.com/vladfi1/peppi", branch = "dev" }
pyo3 = { version = "0.26", features = ["abi3-py310", "extension-module", "generate-import-lib"] }
serde = "1.0"
serde_json = "1.0"

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
codegen-units = 1
incremental = false
rpath = false
