name: Test
on:
  push:
    branches: ['**']
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: dtolnay/rust-toolchain@stable
      - name: Build and install
        uses: PyO3/maturin-action@v1
        with:
          manylinux: auto
          args: --release --out dist
      - name: Install and test
        shell: bash
        run: |
          pip install dist/peppi_py-*.whl --force-reinstall
          pip install pytest
          pytest tests/
